INSERT INTO CATEGORY (DESCRIPTION) VALUES('Magazinesx');
INSERT INTO CATEGORY (DESCRIPTION) VALUES('Movies');
INSERT INTO CATEGORY (DESCRIPTION) VALUES('Books');

INSERT INTO SUPPLIER (NAME) VALUES('Penske Media Corporation');
INSERT INTO SUPPLIER (NAME) VALUES('Amazon');

INSERT INTO PRODUCT (NAME, FK_SUPPLIER, FK_CATEGORY, QUANTITY_AVAILABLE) VALUES('Rolling Stone',1,1,10);
INSERT INTO PRODUCT (NAME, FK_SUPPLIER, FK_CATEGORY, QUANTITY_AVAILABLE) VALUES('Titanic',2,2,5);
INSERT INTO PRODUCT (NAME, FK_SUPPLIER, FK_CATEGORY, QUANTITY_AVAILABLE) VALUES('Zelda',2,3,20);
